import { EventEmitter, OnInit } from '@angular/core';
import { OsTypes } from "../../types/types";
import { NgxDesktopService } from "../../ngx-desktop.service";
import { ToolbarComponent } from "../toolbar/toolbar.component";
import * as i0 from "@angular/core";
export declare class TitleBarComponent implements OnInit {
    private ngxDesktopService;
    toolbarComponent: ToolbarComponent;
    private _os;
    set os(os: OsTypes);
    get os(): OsTypes;
    title: string;
    controls: boolean;
    isFullscreen: boolean;
    transparent: boolean;
    onCloseClick: EventEmitter<any>;
    onMaximizeClick: EventEmitter<any>;
    onMinimizeClick: EventEmitter<any>;
    onResizeClick: EventEmitter<any>;
    windowBlur: boolean;
    mouseover: boolean;
    closeMousedown: boolean;
    minimizeMousedown: boolean;
    maximizeMousedown: boolean;
    minimizeMouseover: boolean;
    closeMouseover: boolean;
    maximizeMouseover: boolean;
    maximized: boolean;
    maximizedChange: EventEmitter<boolean>;
    constructor(ngxDesktopService: NgxDesktopService);
    ngOnInit(): void;
    triggerMaximize(): void;
    static ɵfac: i0.ɵɵFactoryDef<TitleBarComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<TitleBarComponent, "ngx-desktop-title-bar", never, { "os": "os"; "title": "title"; "controls": "controls"; "isFullscreen": "isFullscreen"; "transparent": "transparent"; "maximized": "maximized"; }, { "onCloseClick": "onCloseClick"; "onMaximizeClick": "onMaximizeClick"; "onMinimizeClick": "onMinimizeClick"; "onResizeClick": "onResizeClick"; "maximizedChange": "maximizedChange"; }, ["toolbarComponent"]>;
}
