import { EventEmitter, OnInit } from '@angular/core';
import { OsTypes } from "../../types/types";
import { NgxDesktopService } from "../../ngx-desktop.service";
import * as i0 from "@angular/core";
export declare type MacColor = 'default' | 'blue' | 'pink';
export declare type WindowsColor = string;
export declare class ButtonComponent implements OnInit {
    private ngxDesktopService;
    mousedown: boolean;
    windowBlur: boolean;
    mouseover: boolean;
    disabled: boolean;
    onClick: EventEmitter<MouseEvent>;
    theme: 'light' | 'dark';
    type: 'button' | 'submit';
    size: string | number;
    marginBottom: string | number;
    marginLeft: string | number;
    marginRight: string | number;
    marginTop: string | number;
    paddingBottom: string | number;
    paddingLeft: string | number;
    paddingRight: string | number;
    paddingTop: string | number;
    padding: string | number;
    margin: string | number;
    private _os;
    set os(os: OsTypes);
    get os(): OsTypes;
    private _color;
    darkenColor: string;
    isDarkColor: boolean;
    set color(color: MacColor | WindowsColor);
    get color(): MacColor | WindowsColor;
    get style(): any;
    constructor(ngxDesktopService: NgxDesktopService);
    ngOnInit(): void;
    static ɵfac: i0.ɵɵFactoryDef<ButtonComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<ButtonComponent, "ngx-desktop-button", never, { "disabled": "disabled"; "theme": "theme"; "type": "type"; "size": "size"; "marginBottom": "marginBottom"; "marginLeft": "marginLeft"; "marginRight": "marginRight"; "marginTop": "marginTop"; "paddingBottom": "paddingBottom"; "paddingLeft": "paddingLeft"; "paddingRight": "paddingRight"; "paddingTop": "paddingTop"; "padding": "padding"; "margin": "margin"; "os": "os"; "color": "color"; }, { "onClick": "onClick"; }, never>;
}
