import { OnInit } from '@angular/core';
import { LayoutTypes, OsTypes } from "../../types/types";
import { NgxDesktopService } from "../../ngx-desktop.service";
import { StyleValuePipe } from "../../pipes/style-value.pipe";
import { HorizontalAlignmentTypes } from "../../directives/ngx-desktop-horizontal-alignment.directive";
import { VerticalAlignmentTypes } from "../../directives/ngx-desktop-vertical-alignment.directive";
import * as i0 from "@angular/core";
export declare class ViewComponent implements OnInit {
    private ngxDesktopService;
    private styleValuePipe;
    private _os;
    set os(os: OsTypes);
    get os(): OsTypes;
    horizontalAlignment: HorizontalAlignmentTypes;
    verticalAlignment: VerticalAlignmentTypes;
    height: string | number;
    width: string | number;
    margin: number | string;
    marginTop: number | string;
    marginLeft: number | string;
    marginRight: number | string;
    marginBottom: number | string;
    padding: number | string;
    paddingTop: number | string;
    paddingLeft: number | string;
    paddingRight: number | string;
    paddingBottom: number | string;
    background: string | boolean;
    layout: LayoutTypes;
    constructor(ngxDesktopService: NgxDesktopService, styleValuePipe: StyleValuePipe);
    ngOnInit(): void;
    get styleWidth(): any;
    get styleHeight(): any;
    static ɵfac: i0.ɵɵFactoryDef<ViewComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<ViewComponent, "ngx-desktop-view", never, { "os": "os"; "horizontalAlignment": "horizontalAlignment"; "verticalAlignment": "verticalAlignment"; "height": "height"; "width": "width"; "margin": "margin"; "marginTop": "marginTop"; "marginLeft": "marginLeft"; "marginRight": "marginRight"; "marginBottom": "marginBottom"; "padding": "padding"; "paddingTop": "paddingTop"; "paddingLeft": "paddingLeft"; "paddingRight": "paddingRight"; "paddingBottom": "paddingBottom"; "background": "background"; "layout": "layout"; }, {}, never>;
}
